version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: library_postgres
    restart: always
    environment:
      POSTGRES_USER: dht_admin
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: smart_library
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: library_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  backend:
    build: ./backend-nestjs              # VPS sẽ tự build dựa vào Dockerfile trong thư mục backend-nestjs
    container_name: library_backend
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./backend-nestjs/.env
    environment:
      DATABASE_URL: "postgresql://dht_admin:123456@postgres:5432/smart_library?schema=public"
    volumes:
      - ./backend-nestjs/knowledge:/app/knowledge
      - ./ai-service/data:/app/data
    depends_on:
      - postgres

  ai:
    build: ./ai-service                  # VPS sẽ tự build dựa vào Dockerfile trong thư mục ai-service
    container_name: library_ai
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend-nestjs/knowledge:/app/knowledge   # Chia sẻ thư mục luật từ Backend sang AI
      - ./ai-service/data:/app/data             # Chia sẻ thư mục data (excel, ảnh bìa) sang AI
    depends_on:
      - postgres

  frontend:
    build: ./frontend                    # VPS sẽ tự build dựa vào Dockerfile trong thư mục frontend
    container_name: library_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: