version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: dht_admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: smart_library
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Adminer giúp bạn xem Database qua trình duyệt cực nhanh
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data: